### ISSUE TITLE
Change name?

### ISSUE THREAD

**Issue by faustinoaq** [elorest/git_deploy#1]
Hi @elorest interesting tool, but I think the name is a bit confusing, git_deploy is only for crystal apps, right?

So I would suggest you new crystallist names like:

- crystploy
- creploy
- crygitdep
- cramber
- amberystal
- amberit
- gital
- deploystal

WDYT? 😅 You can close this issue in any moment, is just my crazy idea 😉

**Comment by elorest** [comment]
Potentially. I didn't intend for this to be for crystal only, and most of it isn't. As it currently stands it works out of the box with amber, because of 15 lines at the bottom of the post-receive hook.

Most of it would work well with most other languages though.
